version: 0.2

run-as: root

env:
  variables:
    NEO_DOCS_BUCKET_NAME: "neodapidocs.o3.network"
    NEO_DOCS_DISTRIBUTION_ID: "E3FNU7MRCVVDLZ"
    ONT_DOCS_BUCKET_NAME: "ontdapidocs.o3.network"
    ONT_DOCS_DISTRIBUTION_ID: "EOLLDLPJJG41F"
    DOCS_DISTRIBUTION_ID: "ECTYGKE66GGGC"
    ONT_TESTBED_BUCKET_NAME: "ontdapitestbed.o3.app"
    ONT_TESTBED_DISTRIBUTION_ID: "E3PXLO44HLRNK5"
    NEO_TESTBED_BUCKET_NAME: "neodapitestbed.o3.app"
    NEO_TESTBED_DISTRIBUTION_ID: "EUCWR0DB12L5Z"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - gem install bundler
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - cd packages/neo/docs
      - bundle install
      - cd ../../ont/docs
      - bundle install
  build:
    commands:
      - bundle exec middleman build --clean
      - cd ../../neo/docs
      - bundle exec middleman build --clean
  post_build:
    commands:
      - cd build
      - aws s3 sync . "s3://${NEO_DOCS_BUCKET_NAME}" --delete
      - aws cloudfront create-invalidation --distribution-id "${NEO_DOCS_DISTRIBUTION_ID}" --paths "/*"
      - cd ../../../ont/docs/build
      - aws s3 sync . "s3://${ONT_DOCS_BUCKET_NAME}" --delete
      - aws cloudfront create-invalidation --distribution-id "${ONT_DOCS_DISTRIBUTION_ID}" --paths "/*"
      - aws cloudfront create-invalidation --distribution-id "${DOCS_DISTRIBUTION_ID}" --paths "/*"
      - cd ../../test
      - aws s3 sync . "s3://${ONT_TESTBED_BUCKET_NAME}" --delete
      - aws cloudfront create-invalidation --distribution-id "${ONT_TESTBED_DISTRIBUTION_ID}" --paths "/*"
      - cd ../../neo/test
      - aws s3 sync . "s3://${NEO_TESTBED_BUCKET_NAME}" --delete
      - aws cloudfront create-invalidation --distribution-id "${NEO_TESTBED_DISTRIBUTION_ID}" --paths "/*"
